package check

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestClassifyApproveWhenScopeRespectedAndEvidenceAttached(t *testing.T) {
	task := Task{
		Task:     "bounded change",
		Allowed:  []string{"site/index.html", "site/style.css"},
		Changed:  []string{"site/index.html"},
		Blocked:  []string{"docs/research/**"},
		Evidence: []string{"manual sanity check"},
	}

	result := Classify(task)

	if result.Decision != "approve" {
		t.Fatalf("expected approve, got %q", result.Decision)
	}
	if result.ScopeStatus != "respected" {
		t.Fatalf("expected respected, got %q", result.ScopeStatus)
	}
	if len(result.OutOfScope) != 0 {
		t.Fatalf("expected no out-of-scope files, got %v", result.OutOfScope)
	}
}

func TestClassifyInspectWhenBlockedFileTouched(t *testing.T) {
	task := Task{
		Task:     "drifted change",
		Allowed:  []string{"site/index.html"},
		Changed:  []string{"site/index.html", "docs/research/notes.md"},
		Blocked:  []string{"docs/research/**"},
		Evidence: []string{"manual sanity check"},
	}

	result := Classify(task)

	if result.Decision != "inspect" {
		t.Fatalf("expected inspect, got %q", result.Decision)
	}
	if result.Reason != "blocked files were touched" {
		t.Fatalf("unexpected reason: %q", result.Reason)
	}
	if len(result.BlockedTouched) != 1 || result.BlockedTouched[0] != "docs/research/notes.md" {
		t.Fatalf("unexpected blocked touched set: %v", result.BlockedTouched)
	}
}

func TestRenderMarkdownIncludesDecisionAndEvidence(t *testing.T) {
	task := Task{
		Task:     "artifact drawer",
		Allowed:  []string{"site/index.html"},
		Changed:  []string{"site/index.html"},
		Blocked:  []string{"docs/research/**"},
		Evidence: []string{"drawer opens required artifacts"},
	}

	content := RenderMarkdown(task, Classify(task))

	expected := []string{
		"# Generated Review Artifact",
		"Decision: approve",
		"- `site/index.html`",
		"drawer opens required artifacts",
	}

	for _, fragment := range expected {
		if !strings.Contains(content, fragment) {
			t.Fatalf("expected rendered markdown to contain %q", fragment)
		}
	}
}

func TestGenerateFromFileUsesPlainTextManifestOverride(t *testing.T) {
	tempDir := t.TempDir()
	taskPath := filepath.Join(tempDir, "task.json")
	manifestPath := filepath.Join(tempDir, "changed.txt")

	taskJSON := `{
  "task": "bounded manifest change",
  "allowed": ["site/index.html"],
  "blocked": ["docs/research/**"],
  "changed": ["docs/research/notes.md"],
  "evidence": ["manual sanity check"]
}`
	if err := os.WriteFile(taskPath, []byte(taskJSON), 0o644); err != nil {
		t.Fatalf("write task: %v", err)
	}
	if err := os.WriteFile(manifestPath, []byte("# generated by runner\nsite/index.html\n"), 0o644); err != nil {
		t.Fatalf("write manifest: %v", err)
	}

	content, err := GenerateFromFile(taskPath, GenerateOptions{
		ChangedManifestPath: manifestPath,
	})
	if err != nil {
		t.Fatalf("generate from file: %v", err)
	}
	if !strings.Contains(content, "Decision: approve") {
		t.Fatalf("expected approve decision, got:\n%s", content)
	}
	if strings.Contains(content, "docs/research/notes.md") {
		t.Fatalf("expected manifest override to replace task changed files, got:\n%s", content)
	}
}

func TestGenerateFromFileUsesJSONManifestAndDetectsDrift(t *testing.T) {
	tempDir := t.TempDir()
	taskPath := filepath.Join(tempDir, "task.json")
	manifestPath := filepath.Join(tempDir, "changed.json")

	taskJSON := `{
  "task": "drifted manifest change",
  "allowed": ["site/index.html"],
  "blocked": ["wrangler.toml"],
  "evidence": ["manual sanity check"]
}`
	if err := os.WriteFile(taskPath, []byte(taskJSON), 0o644); err != nil {
		t.Fatalf("write task: %v", err)
	}
	if err := os.WriteFile(manifestPath, []byte("[\"site/index.html\", \"wrangler.toml\"]\n"), 0o644); err != nil {
		t.Fatalf("write manifest: %v", err)
	}

	content, err := GenerateFromFile(taskPath, GenerateOptions{
		ChangedManifestPath: manifestPath,
	})
	if err != nil {
		t.Fatalf("generate from file: %v", err)
	}
	if !strings.Contains(content, "Decision: inspect") {
		t.Fatalf("expected inspect decision, got:\n%s", content)
	}
	if !strings.Contains(content, "- `wrangler.toml`") {
		t.Fatalf("expected rendered markdown to include blocked file from manifest, got:\n%s", content)
	}
}

func TestGenerateFromFileUsesDiffOverride(t *testing.T) {
	tempDir := t.TempDir()
	taskPath := filepath.Join(tempDir, "task.json")
	diffPath := filepath.Join(tempDir, "changed.patch")

	taskJSON := `{
  "task": "bounded diff change",
  "allowed": ["site/index.html", "site/style.css"],
  "blocked": ["docs/research/**"],
  "changed": ["docs/research/notes.md"],
  "evidence": ["manual sanity check"]
}`
	diffBody := `diff --git a/site/index.html b/site/index.html
index 1111111..2222222 100644
--- a/site/index.html
+++ b/site/index.html
@@ -1 +1 @@
-before
+after
diff --git a/site/style.css b/site/style.css
index 3333333..4444444 100644
--- a/site/style.css
+++ b/site/style.css
@@ -1 +1 @@
-before
+after
`
	if err := os.WriteFile(taskPath, []byte(taskJSON), 0o644); err != nil {
		t.Fatalf("write task: %v", err)
	}
	if err := os.WriteFile(diffPath, []byte(diffBody), 0o644); err != nil {
		t.Fatalf("write diff: %v", err)
	}

	content, err := GenerateFromFile(taskPath, GenerateOptions{
		ChangedDiffPath: diffPath,
	})
	if err != nil {
		t.Fatalf("generate from file: %v", err)
	}
	if !strings.Contains(content, "Decision: approve") {
		t.Fatalf("expected approve decision, got:\n%s", content)
	}
	if strings.Contains(content, "docs/research/notes.md") {
		t.Fatalf("expected diff override to replace task changed files, got:\n%s", content)
	}
}

func TestLoadChangedDiffSupportsUnifiedDiffFallback(t *testing.T) {
	tempDir := t.TempDir()
	diffPath := filepath.Join(tempDir, "changed.patch")
	diffBody := `--- site/index.html	2026-03-12
+++ site/index.html	2026-03-12
@@ -1 +1 @@
-before
+after
--- wrangler.toml	2026-03-12
+++ wrangler.toml	2026-03-12
@@ -1 +1 @@
-before
+after
`
	if err := os.WriteFile(diffPath, []byte(diffBody), 0o644); err != nil {
		t.Fatalf("write diff: %v", err)
	}

	changed, err := LoadChangedDiff(diffPath)
	if err != nil {
		t.Fatalf("load changed diff: %v", err)
	}
	if len(changed) != 2 {
		t.Fatalf("expected 2 changed files, got %v", changed)
	}
	if changed[0] != "site/index.html" || changed[1] != "wrangler.toml" {
		t.Fatalf("unexpected changed files: %v", changed)
	}
}

func TestGenerateFromFileUsesGitRange(t *testing.T) {
	repoDir := t.TempDir()
	runGit(t, repoDir, "init")
	runGit(t, repoDir, "config", "user.name", "Specpunk Test")
	runGit(t, repoDir, "config", "user.email", "specpunk@example.com")

	writeFile(t, filepath.Join(repoDir, "site/index.html"), "before\n")
	writeFile(t, filepath.Join(repoDir, "site/style.css"), "before\n")
	runGit(t, repoDir, "add", ".")
	runGit(t, repoDir, "commit", "-m", "baseline")

	writeFile(t, filepath.Join(repoDir, "site/index.html"), "after\n")
	writeFile(t, filepath.Join(repoDir, "site/style.css"), "after\n")
	runGit(t, repoDir, "add", ".")
	runGit(t, repoDir, "commit", "-m", "bounded change")

	taskPath := filepath.Join(repoDir, "task.json")
	taskJSON := `{
  "task": "bounded git range change",
  "allowed": ["site/index.html", "site/style.css"],
  "blocked": ["docs/research/**"],
  "evidence": ["manual sanity check"]
}`
	writeFile(t, taskPath, taskJSON)

	content, err := GenerateFromFile(taskPath, GenerateOptions{
		ChangedGitRange: "HEAD~1..HEAD",
		WorkingDir:      repoDir,
	})
	if err != nil {
		t.Fatalf("generate from file: %v", err)
	}
	if !strings.Contains(content, "Decision: approve") {
		t.Fatalf("expected approve decision, got:\n%s", content)
	}
	if !strings.Contains(content, "- `site/index.html`") || !strings.Contains(content, "- `site/style.css`") {
		t.Fatalf("expected git-derived changed files, got:\n%s", content)
	}
}

func TestGenerateFromFileUsesGitRangeAndDetectsDrift(t *testing.T) {
	repoDir := t.TempDir()
	runGit(t, repoDir, "init")
	runGit(t, repoDir, "config", "user.name", "Specpunk Test")
	runGit(t, repoDir, "config", "user.email", "specpunk@example.com")

	writeFile(t, filepath.Join(repoDir, "site/index.html"), "before\n")
	writeFile(t, filepath.Join(repoDir, "docs/research/notes.md"), "before\n")
	runGit(t, repoDir, "add", ".")
	runGit(t, repoDir, "commit", "-m", "baseline")

	writeFile(t, filepath.Join(repoDir, "site/index.html"), "after\n")
	writeFile(t, filepath.Join(repoDir, "docs/research/notes.md"), "after\n")
	runGit(t, repoDir, "add", ".")
	runGit(t, repoDir, "commit", "-m", "drift change")

	taskPath := filepath.Join(repoDir, "task.json")
	taskJSON := `{
  "task": "drifted git range change",
  "allowed": ["site/index.html"],
  "blocked": ["docs/research/**"],
  "evidence": ["manual sanity check"]
}`
	writeFile(t, taskPath, taskJSON)

	content, err := GenerateFromFile(taskPath, GenerateOptions{
		ChangedGitRange: "HEAD~1..HEAD",
		WorkingDir:      repoDir,
	})
	if err != nil {
		t.Fatalf("generate from file: %v", err)
	}
	if !strings.Contains(content, "Decision: inspect") {
		t.Fatalf("expected inspect decision, got:\n%s", content)
	}
	if !strings.Contains(content, "- `docs/research/notes.md`") {
		t.Fatalf("expected drifted git-derived file, got:\n%s", content)
	}
}

func writeFile(t *testing.T, path string, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", path, err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func runGit(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %v failed: %v\n%s", args, err, fmt.Sprintf("%s", output))
	}
}
