use super::artifacts::{ArtifactSet, Convention, ConversionConfidence};
use super::InitError;
use std::path::Path;

/// Answers to the 3 greenfield questions.
#[derive(Debug, Clone)]
pub struct GreenFieldAnswers {
    /// What are you building?
    pub description: String,
    /// What tech stack?
    pub tech_stack: String,
    /// What's never in scope?
    pub never_in_scope: String,
}

impl Default for GreenFieldAnswers {
    fn default() -> Self {
        GreenFieldAnswers {
            description: "New project".to_string(),
            tech_stack: "unknown".to_string(),
            never_in_scope: "".to_string(),
        }
    }
}

/// Run greenfield initialization with the provided answers.
/// Does not touch stdin — answers must be pre-filled (testable design).
pub fn run_greenfield(root: &Path, answers: &GreenFieldAnswers) -> Result<ArtifactSet, InitError> {
    let config_toml = build_greenfield_config(answers);
    let intent_md = build_greenfield_intent(answers);
    let conventions = build_greenfield_conventions(root);
    let conventions_json = serde_json::to_string_pretty(&conventions)
        .map_err(|e| InitError::Serialize(e.to_string()))?;

    Ok(ArtifactSet {
        config_toml,
        intent_md,
        conventions_json,
        scan_json: None, // greenfield has no scan.json
    })
}

fn build_greenfield_config(answers: &GreenFieldAnswers) -> String {
    let stack = &answers.tech_stack;
    format!(
        r#"# punk configuration — auto-generated by punk init (greenfield)
# https://github.com/heurema/specpunk

[project]
description = "{}"
tech_stack = "{stack}"

[vcs]
preferred = "auto"

[provider]
# LLM provider configuration (Phase 1)
# api_key = ""
# model = ""
"#,
        answers.description.replace('"', "\\\"")
    )
}

fn build_greenfield_intent(answers: &GreenFieldAnswers) -> String {
    let never = if answers.never_in_scope.is_empty() {
        "_none specified_".to_string()
    } else {
        answers
            .never_in_scope
            .split(',')
            .map(|s| format!("- {}", s.trim()))
            .collect::<Vec<_>>()
            .join("\n")
    };

    format!(
        r#"# Project Intent

<!-- Edit this file to describe your project. punk init will not overwrite it once edited. -->

## What does this project do?

{}

## Tech stack

{}

## Scope boundaries

### Never in scope
{}

## Notes

_Generated by `punk init` (greenfield mode)_
"#,
        answers.description, answers.tech_stack, never
    )
}

fn build_greenfield_conventions(root: &Path) -> Vec<Convention> {
    let mut conventions = Vec::new();

    // Check if there are any convention files already present
    for authoritative in &["CLAUDE.md", "AGENTS.md"] {
        if root.join(authoritative).exists() {
            conventions.push(Convention {
                name: format!("authoritative-{authoritative}"),
                value: format!("{authoritative} found"),
                confidence: ConversionConfidence::Authoritative,
                source: authoritative.to_string(),
            });
        }
    }

    if conventions.is_empty() {
        conventions.push(Convention {
            name: "greenfield-defaults".to_string(),
            value: "no conventions detected yet".to_string(),
            confidence: ConversionConfidence::Low,
            source: "inference".to_string(),
        });
    }

    conventions
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    #[test]
    fn init_greenfield() {
        let tmp = TempDir::new().unwrap();
        let dir = tmp.path();

        let answers = GreenFieldAnswers {
            description: "A test project".to_string(),
            tech_stack: "Rust + Axum".to_string(),
            never_in_scope: "migrations, vendor".to_string(),
        };

        let artifacts = run_greenfield(dir, &answers).unwrap();
        assert!(!artifacts.config_toml.is_empty());
        assert!(!artifacts.intent_md.is_empty());
        assert!(!artifacts.conventions_json.is_empty());
        assert!(
            artifacts.scan_json.is_none(),
            "greenfield must not have scan.json"
        );

        // Write and verify no scan.json is created
        super::super::artifacts::write_artifacts(dir, &artifacts, false).unwrap();

        assert!(dir.join(".punk/config.toml").exists());
        assert!(dir.join(".punk/intent.md").exists());
        assert!(dir.join(".punk/conventions.json").exists());
        assert!(
            !dir.join(".punk/scan.json").exists(),
            "scan.json must not exist in greenfield"
        );

        // Verify content
        let intent = fs::read_to_string(dir.join(".punk/intent.md")).unwrap();
        assert!(intent.contains("A test project"));
        assert!(intent.contains("Rust + Axum"));
    }
}
